apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keyfront-bff.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "keyfront-bff.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keyfront-bff.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "keyfront-bff.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "keyfront-bff.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "keyfront-bff.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          env:
            # Node.js Configuration
            - name: NODE_ENV
              value: {{ .Values.config.nodeEnv | quote }}
            - name: PORT
              value: {{ .Values.config.port | quote }}
            
            # Session Configuration
            - name: SESSION_COOKIE_NAME
              value: {{ .Values.config.sessionCookieName | quote }}
            - name: SESSION_MAX_AGE
              value: {{ .Values.config.sessionMaxAge | quote }}
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "keyfront-bff.secretName" . }}
                  key: {{ .Values.secrets.keys.sessionSecret }}
            
            # CORS Configuration
            - name: CORS_ORIGINS
              value: {{ .Values.config.corsOrigins | quote }}
            
            # Rate Limiting Configuration
            - name: RATE_LIMIT_RPM
              value: {{ .Values.config.rateLimitRpm | quote }}
            
            # Keycloak Configuration
            - name: KC_ISSUER_URL
              value: {{ .Values.keycloak.issuerUrl | quote }}
            - name: KC_CLIENT_ID
              value: {{ .Values.keycloak.clientId | quote }}
            - name: KC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "keyfront-bff.secretName" . }}
                  key: {{ .Values.secrets.keys.keycloakClientSecret }}
            - name: KC_REDIRECT_URI
              value: {{ .Values.keycloak.redirectUri | quote }}
            - name: KC_LOGOUT_REDIRECT_URI
              value: {{ .Values.keycloak.logoutRedirectUri | quote }}
            
            # Redis Configuration
            {{- if .Values.redis.url }}
            - name: REDIS_URL
              value: {{ .Values.redis.url | quote }}
            {{- else }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: REDIS_DATABASE
              value: {{ .Values.redis.database | quote }}
            {{- if .Values.redis.password }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "keyfront-bff.secretName" . }}
                  key: {{ .Values.secrets.keys.redisPassword }}
            {{- end }}
            {{- end }}
            
            # Downstream API Configuration
            {{- if .Values.downstreamApi.baseUrl }}
            - name: DOWNSTREAM_API_BASE
              value: {{ .Values.downstreamApi.baseUrl | quote }}
            {{- end }}
            
            # Additional environment variables
            {{- range .Values.extraEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          
          {{- if or .Values.extraEnvVarsSecret .Values.extraEnvVarsConfigMap }}
          envFrom:
            {{- if .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.extraEnvVarsSecret }}
            {{- end }}
            {{- if .Values.extraEnvVarsConfigMap }}
            - configMapRef:
                name: {{ .Values.extraEnvVarsConfigMap }}
            {{- end }}
          {{- end }}
          
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}