{{- if .Values.secrets.create }}
{{- include "keyfront-bff.validateValues" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keyfront-bff.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "keyfront-bff.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    # Helm hook to create secret before deployment
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  # Session Secret
  {{- if .Values.config.sessionSecret }}
  {{ .Values.secrets.keys.sessionSecret }}: {{ .Values.config.sessionSecret | b64enc | quote }}
  {{- else }}
  {{ .Values.secrets.keys.sessionSecret }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  
  # Keycloak Client Secret
  {{ .Values.secrets.keys.keycloakClientSecret }}: {{ .Values.keycloak.clientSecret | b64enc | quote }}
  
  # Redis Password (if provided)
  {{- if .Values.redis.password }}
  {{ .Values.secrets.keys.redisPassword }}: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
{{- end }}